import React from 'react';
import Head from 'next/head';

const HeadPages = ({ name, description }) => {
  return (
    <Head>
        {!description ?
            ( <title>{ name }</title>)
            :
            (<title>{ name } || { description } </title>)
        }
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/commitive-logo-3.png" />
    </Head>
  )
};

export default HeadPages;